name: Bun CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          echo SERVER_URL=${{ secrets.SERVER_URL_PROD }} >> .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker-compose up -d --build
