name: Bun CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          echo SERVER_URL=${{ secrets.SERVER_URL_PROD }} >> .env
      - name: Move project folder up
        run: rsync -av --remove-source-files ./ ..
      - name: Install dependencies
        run: cd .. && bun install
      - name: Build
        run: cd .. && bun run build
